### ISSUE TITLE
rust-onig is entirely broken with Oniguruma 6.9.2

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-onig/rust-onig#103]
```rust
---- names::tests::test_regex_names stdout ----
thread 'names::tests::test_regex_names' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[("foo", [1]), ("bar", [2, 3])]`', src/names.rs:176:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
failures:
    names::tests::test_regex_names
test result: FAILED. 40 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

This is with system installed `oniguruma v6.9.2`.

**Comment by ignatenkobrain** [comment]
oh, this is not surprising since structs inside oniguruma have changed in the 6.9.2...

https://github.com/kkos/oniguruma/commit/f000bbb7729bd250c6de006880c0cbbeaca6efb3#diff-9dd123bdc0c660c5041c3f963fea75b1R914

**Comment by iwillspeak** [comment]
Thanks for this. I’ll look at updating the structs and  and publishing a version of onig-sys compatible with 6.9.2.

**Comment by ignatenkobrain** [comment]
@iwillspeak amazing, thanks a lot!
