### ISSUE TITLE
WIP wasm32-unknown-emscripten cross build

### ISSUE THREAD

**Issue by lopopolo** [rust-onig/rust-onig#106]
Hi, I have a WIP branch to enable a wasm32 cross build of onig. I understand that not all commits may be mergable, but I am hoping to upstream enough so that my fork is unnecessary.

https://github.com/artichoke/rust-onig/tree/wasm

onig still fails to link under emscripten, but I was hoping to find out if you'd accept these changes.

**Comment by iwillspeak** [comment]
I'd be happy to accept a PR. We can work on getting the changes merged in there.

**Comment by lopopolo** [comment]
Thanks @iwillspeak I'll put together a PR. Leaving a note here that to build under wasm32-unknown-unknown requires a clang with this fix:

https://bugs.llvm.org/show_bug.cgi?id=42498
