### ISSUE TITLE
Build fails with system library if it does not include any path

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-onig/rust-onig#119]
```
⋊> ~/P/s/r/r/onig_sys-69.2.0 on master ◦ pkg-config --cflags oniguruma                                                                                                      05:57:22

```

as you can see, the output is empty, so `for path in lib.include_paths {` is doing nothing and bindings.rs are not generated.

**Comment by kaniini** [comment]
This appears to be an issue between pkgconf and the rust pkg_config crate.  pkgconf has a feature where it simplifies the CFLAGS and LIBS based on what it knows about how the system toolchain functions.  I'll open an issue in the pkg_config crate asking them to disable this feature via environmental variables when invoking pkg-config.
