### ISSUE TITLE
`clang-sys` Sometimes Can't Find `libclang`

### ISSUE THREAD

**Issue by qtfkwk** [rust-onig/rust-onig#123]
```text
$ git clone https://github.com/rust-onig/rust-onig.git
$ cd rust-onig
$ git log -n 1
commit 1de4269744c23c8f59d3335077213f85e0a29e18
Author: Will Speak <lithiumflame@gmail.com>
Date:   Tue Oct 1 07:11:03 2019 +0100

    Update `pkg-config` Crate to Fix Missing CFLAGS

    Some platforms require `pkgconfig` to be told to include system CFLAGS
    otherwise we can't compile against the system copy of `onig`. This
    updates the dependent crate to fix the issue.

    Fixes: #119
$ cargo clean
$ cargo build
...
   Compiling onig_sys v69.2.0 (/home/qtfkwk/rust-onig/rust-onig/onig_sys)
error: failed to run custom build command for `onig_sys v69.2.0 (/home/qtfkwk/rust-onig/rust-onig/onig_sys)`

Caused by:
  process didn't exit successfully: `/home/qtfkwk/rust-onig/rust-onig/target/debug/build/onig_sys-0975fb7a2420ab75/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

```text
$ rustup update
...
   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.38.0 (625451e37 2019-09-23)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.40.0-nightly (032a53a06 2019-10-03)
```

```text
$ ls -lh libclang{,AST}.*
lrwxrwxrwx. 1 root root   16 Oct  1 14:46 libclangAST.so -> libclangAST.so.7
-rwxr-xr-x. 1 root root 3.5M Jan 24  2019 libclangAST.so.7
lrwxrwxrwx. 1 root root   13 Oct  1 14:46 libclang.so -> libclang.so.7
-rwxr-xr-x. 1 root root 546K Jan 24  2019 libclang.so.7
```

```text
$ file /usr/lib64/clang-private/libclang{,AST}.so.7
/usr/lib64/clang-private/libclang.so.7:    ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=8585019abeba38846686d1a1a2a1852a0102466f, stripped
/usr/lib64/clang-private/libclangAST.so.7: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=af53e177be1768c1becd8b39d871b24beacfc676, stripped
```

```text
$ sudo yum check-updates >/dev/null; echo $?
0
```

Error persists...

* Using rust stable (1.38) or nightly
* OS is up-to-date
* Files are there and no obvious reason cargo cannot "see" them

This issue may relate to #109 (?).

**Comment by qtfkwk** [comment]
https://github.com/mimblewimble/grin/issues/1606#issuecomment-426404473 => https://github.com/KyleMayes/clang-sys suggests setting `LIBCLANG_PATH`... however that does not change the outcome:

```
$ export LIBCLANG_PATH=/usr/lib64/clang-private
$ echo $LIBCLANG_PATH
/usr/lib64/clang-private
$ cargo build
   Compiling onig_sys v69.2.0
error: failed to run custom build command for `onig_sys v69.2.0`

Caused by:
  process didn't exit successfully: `/home/qtfkwk/project/target/debug/build/onig_sys-7c95ff416c85f782/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by qtfkwk** [comment]
Tracing the dependencies... my project has `syntect = "3.3.0"`... syntect has `onig = { version = "5.0", optional = true }` ( https://github.com/trishume/syntect/blob/master/Cargo.toml#L22 ), and onig has `version = "69.2.0"` ( https://github.com/rust-onig/rust-onig/blob/master/onig/Cargo.toml#L35 )... so how can a downstream project control a breaking change like this?

**Comment by qtfkwk** [comment]
updated first comment with more direct procedure to reproduce

**Comment by iwillspeak** [comment]
Thanks for this. Hopefully a good mitigation for this will be a switch back to pre-generated bindings for selected architectures. In the mean time do you have an `llvm-config` executable anywhere? Apparently `clang-sys` can use that to find a version of `libclang` that works.

**Comment by qtfkwk** [comment]
> Thanks for this. Hopefully a good mitigation for this will be a switch back to pre-generated bindings for selected architectures. In the mean time do you have an `llvm-config` executable anywhere? Apparently `clang-sys` can use that to find a version of `libclang` that works.

```
$ llvm-config --prefix
/usr
```

**Comment by qtfkwk** [comment]
Did some more investigation... and recalled that this was working just fine on the same machine/OS days ago when it was running in server/headless mode (without X.Org/GUI, command line only); problems started after running `sudo yum groupinstall "Server with GUI"` which subsequently installed the `llvm-private` package that provided the files that cargo/rust is now complaining about:

```
$ yum whatprovides libclangAST.so.7
llvm-private-7.0.1-1.el7.i686 : llvm engine for Mesa
Repo        : rhel-7-server-rpms
Matched from:
Provides    : libclangAST.so.7
```

Unsure what files it used prior... still investigating.

Also considering moving my Linux/Rust build environment into either a [container](https://hub.docker.com/_/rust/) or a VM to avoid such interference by the distro.

**Comment by qtfkwk** [comment]
No other libclangAST.so* files on the system:

```
$ sudo find / -name 'libclangAST.so*'
/usr/lib64/clang-private/libclangAST.so
/usr/lib64/clang-private/libclangAST.so.7
```

**Comment by qtfkwk** [comment]
Okay... some progress... in the original project I experienced this issue (that depends on syntect) the following enabled a clean build:

```
sudo yum install -y llvm-toolset-7
export LIBCLANG_PATH=/opt/rh/llvm-toolset-7/root/usr/lib64
cargo build
```

However in the attempt to build rust-onig following the above, I see now:

```
$ cargo build
   Compiling onig_sys v69.2.0 (/home/qtfkwk/rust-onig/rust-onig/onig_sys)
error: failed to run custom build command for `onig_sys v69.2.0 (/home/qtfkwk/rust-onig/rust-onig/onig_sys)`

Caused by:
  process didn't exit successfully: `/home/qtfkwk/rust-onig/rust-onig/target/debug/build/onig_sys-c889e7f53a20ea3e/build-script-build` (exit code: 101)
--- stderr
error: header 'oniguruma/src/oniguruma.h' does not exist.
thread 'main' panicked at 'bindgen: ()', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Which I assume indicates a need to install the onigurama library, right?

**Comment by iwillspeak** [comment]
The error you're up against now is that you're compiling rust-onig but the git submodules aren't all checked out. I recommend you try running `git submodule update --init`. You should then be able to build.

The build is looking for the header file in the bundled oniguruma source file. This probably means it can't find a sytem version of libonig to use and will compile oniguruma from the bundled source.

**Comment by jensim** [comment]
Not sure how interested you are in this, but `onig` is quite a popular download from crates.io, so I thought I'd drop a line at least..
Latest version of bindgen 0.55.x uses clang-sys 1.x.x, stable version might be nice to use.
Not sure if this fits into this discussion or not, just that it might ;-)

**Comment by iwillspeak** [comment]
Thanks for the headsup @jensim . As of #147 we now use bindgen 0.55. This should be arriving in Onig for version 6.1.0 🤞.

Closing this issue as I'm not sure there's any Onig work that is needed related to this.
