### ISSUE TITLE
Can stack-checking be disabled when compiling the crate?

### ISSUE THREAD

**Issue by mkYYY** [rust-onig/rust-onig#129]
Hello, 
First, I am new to rust and posting an issue on GitHub, so please let me know if the terminology or what I'm doing are wrong. 
The original issue is sharkdp/bat#680 ([my comment](https://github.com/sharkdp/bat/issues/680#issuecomment-552126590)). 

On builds for macOS 10.15.x Catalina, it seems `match_at` function from `regexec.c` emits assembly codes (or equivalent machine codes) calling `___chkstk_darwin` library function in `/usr/lib/system/libsystem_pthread.dylib`. For *clang*, such codes are generated if there is `-fstack-check` option and it is the default option for macOS 10.15.x's clang 11.0.0. 
I have checked with LLDB that during the call to this function, the value of `r10` register was overwritten to a pointer to somewhere on the stack (0x7FEF...). Then, if there is `jmp *(%r10)` instruction or similar (the case for [sharkdp/bat](https://github.com/sharkdp/bat)), SIGSEGV occurs. 
I patched *bat* binary in question by substituting `call ____chkstk_darwin` to `nop`s, then it operated successfully. 
I guess other projects using *rust-onig* may have the similar problems.  
Could you consider building the crate (?) with `-fstack-check` or equivalent rustc's options disabled as a (temporary) workaround for macOS 10.15.x?

**Comment by iwillspeak** [comment]
Thanks for this issue. Apologies for the latent reply. I'll look into it.

**Comment by iwillspeak** [comment]
This should have been fixed by #127 .
