### ISSUE TITLE
Clone implementation for onig::Regex

### ISSUE THREAD

**Issue by lopopolo** [rust-onig/rust-onig#131]
Is there anything preventing `Regex` from having a `Clone` implementation?

I am trying pass multiple copies of a `Regex` around and to do that requires that I reparse the pattern for every copy.

**Comment by iwillspeak** [comment]
I don’t know if the underlying object can be used concurrently. You could use an `Arc` maybe to share a regex without crossing thread boundaries.

Often regex have internal miracle scratch space that prevents you just copying the pointer and using the same object from multiple places.

**Comment by iwillspeak** [comment]
Sorry. Brain fart on my part this morning I think. You're asking about Clone not about sharing Across threads. The `onig::Regex` type is already marked as `Sync` and can be shared across threads. The `onig::Regex` type holds a reference to a native object that must be disposed once. To implement clone we would have to keep a reference count _inside_ the `onig::Regex` type. That would bloat the type and add overhead for people who don't want to clone their regex.

Searching and other operations on a regex don't require mutable access so you should be able to just pass around a reference without needing to clone.

If you absolutely must have an object which you can call `Clone` on then you can wrap the regex in an `Arc` or `Rc`.
