### ISSUE TITLE
Question about regex replace.

### ISSUE THREAD

**Issue by oronsh** [rust-onig/rust-onig#158]
Hello, 
Iets say I have this text:
```rust
let text = "{\"ops\":\"G1\",\"user\":\"John Smith-2125 Sierra Ventura Dr.-Sunnyvale-CA-94054\",\"status\":\"305\"}";
```

and I want to do the following replacement:
```rust
let re = Regex::new(r#"(.*user"):"([^-]*)-([^-]*)-([^-]*)-([^-]*)-([^-]*)",([^$]*)"#).unwrap();
let replace_value = r#"$1:{\"name\":\"$2\",\"address\":\"$3\",\"city\":\"$4\",\"state\":\"$5\",\"zip\":\"$6\"},$7"#;
re.replace_all(text, replace_value);
```

I want the result to be like this:
```rust
r#"{"ops":"G1","user":{\"name\":\"John Smith\",\"address\":\"2125 Sierra Ventura Dr.\",\"city\":\"Sunnyvale\",\"state\":\"CA\",\"zip\":\"94054\"},"status":"305"}"#
```

but instead I get my replaced value:
```rust
 r#"$1:{\"name\":\"$2\",\"address\":\"$3\",\"city\":\"$4\",\"state\":\"$5\",\"zip\":\"$6\"},$7"#;
```

Is there a way I can achieve that?
Thanks a lot!

**Comment by oronsh** [comment]
Just solved it with the dollar example 
https://github.com/rust-onig/rust-onig/blob/main/onig/examples/dollar.rs

Is it like that in oniguruma also?

**Comment by iwillspeak** [comment]
I think oniguruma just gives you the indices where things match. Replacement is done entirely by this library. Most of the heavy lifting is delegated to the replacer trait.
