### ISSUE TITLE
The proposal to merge the two projects

### ISSUE THREAD

**Issue by defuz** [rust-onig/rust-onig#2]
Hello!

A month ago, I needed binding for oniguruma library in Rust, and I found your project. Unfortunately, it did not implement everything that I needed, and looked as if you do not maintain it anymore. So, I decided to use your achievements to make a more comprehensive binding and put it in crates ([repo](https://github.com/defuz/oniguruma), [crate](https://crates.io/crates/oniguruma/)). I hope you do not mind this. I wanted to contact you, but unfortunately did not find your email.

Today I noticed that you continue to develop your project. I believe that we have common goals, so I propose to merge them into one, so as not to perform the same work twice. My main vision is to realize the full binding, which reproduces API of [regex library](https://github.com/rust-lang-nursery/regex) as much as possible, but at the same time provides all the advantages of the Oniguruma library (using Regions, capture tree traversing, etc)

I will be glad to hear what you think about it.

**Comment by iwillspeak** [comment]
That sounds interesting. I'm glad you found my code useful.

I had a similar plan of working towards an API like the rust regex one, but with all of the Oniguruma goodness included. I'll have a look at your code and see what the best way of merging these two is.

What would you suggest?

**Comment by iwillspeak** [comment]
Looks like you've got some pretty nice improvements to the rust side of things. I'm a fan of the captures object. I was just trying to work out how to implement something like that myself. 

My current plan would be this:

Create a new girhub org and transfer ownership of rust-onig to it. Add your repo as a sub module and pick the changes out of it in a separate branch (subtree merge style).

 I'll have a go at that this evening if it is ok with you. I notice that your repo doesn't have a license file but is MIT in the cargo file. I assume it is ok for me to treat it as MIT?

**Comment by defuz** [comment]
> Add your repo as a sub module and pick the changes out of it in a separate branch (subtree merge style).

I'm not sure I fully understand what you want to do, but feel free to start. :) The main thing I want to avoid is duplication of capabilities in different project.

> I assume it is ok for me to treat it as MIT?

Yes

**Comment by iwillspeak** [comment]
Ok. I will have a go at this this evening hopefully. I've invited you to
the organisation I created so you should be able to contribute to the repo
now.

**Comment by defuz** [comment]
> I've invited you to the organisation I created so you should be able to contribute to the repo now.

I accept your invite, but do not have write access to the repository. You have to change my permissions separately.

**Comment by defuz** [comment]
@iwillspeak I have created PR that makes changes to `onig-sys` that are necessary for unification of projects. Please review it and tell what you think. Later I will prepare a few PR's that make changes to `onig` crates.

**Comment by iwillspeak** [comment]
All looks good. :+1: . I'll close this issue now.
