### ISSUE TITLE
Implement `Iterator::size_hint` for our Iterator Implementations

### ISSUE THREAD

**Issue by iwillspeak** [rust-onig/rust-onig#20]
We should implement the `size_hint` method when we know what it is. This is possible for things like captures and capture names where we know bounds.

We currently have the following iterators:

- [ ] SubCaptures<'t>
- [ ] SubCapturesPos<'t>
- [ ] ~~FindMatches<'r, 't>~~
- [ ] ~~FindCaptures<'r, 't>~~
- [ ] ~~RegexSplits<'r, 't>~~
- [ ] RegexSplitsN<'r, 't>
- [ ] CaptureNames<'r>
- [ ] CaptureTreeNodeIter<'t>

**Comment by iwillspeak** [comment]
If you want to work on one of these for Hacktoberfest please comment on this issue claiming one beforehand to avoid duplicating effort. Happy hacking!

**Comment by b52** [comment]
@iwillspeak I would take this one. :+1:

**Comment by iwillspeak** [comment]
Cool. Are you up for implementing this for all the iterators?

**Comment by b52** [comment]
I'll try, I if hit a roadblock I would message you.

**Comment by iwillspeak** [comment]
Good luck. Looking forward to your pull request. :+1:

**Comment by b52** [comment]
I don't thick it is possible to implement `size_hint()` for `FindMatches`, `FindCaptures` and the derived `RegexSplits` and `RegexSplitsN` types, due to their dynamic nature.

**Comment by b52** [comment]
Well, it's possible to give the upper bound for `RegexSplitsN`.

**Comment by iwillspeak** [comment]
Yes, best leave `FindMatches` and `FindCaptures`. If you could put a simple upper bound in `RegexSplitsN` that would be nice though.
