### ISSUE TITLE
Re-Create the Oniguruma Samples

### ISSUE THREAD

**Issue by iwillspeak** [rust-onig/rust-onig#21]
The [oniguruma samples directory](https://github.com/kkos/oniguruma/tree/master/sample) contains some useful examples of the API. We should convert these into runnable examples in this project.
- [x] sample/simple.c
- [x] sample/names.c (@b52)
- [x] sample/encode.c (@iwillspeak)
- [x] sample/listcap.c
- [x] sample/scan.c
- [x] sample/sql.c
- [x] sample/user_property.c
- [x] sample/syntax.c
- ~sample/crnl.c~

Anyone is free to shout up and claim any of these.

**Comment by iwillspeak** [comment]
For the encoding samples we're going to need the ability to specify the encoding you're using when creating a regex and performing a search (#23).

**Comment by iwillspeak** [comment]
For the scan sample we're going to need support for the `onig_scan` API (#24).

**Comment by iwillspeak** [comment]
Anyone interested in tackling one or more of these samples for Hacktoberfest please comment on this issue claiming one before starting work to avoid duplicating effort. Happy hacking!

**Comment by b52** [comment]
I'll take the `sample/names.c` example.

**Comment by b52** [comment]
Do I somewhat have to implement a new API for `onig_foreach_name`? It doesn't seem it has a public API except for the onig-sys one?

**Comment by iwillspeak** [comment]
Yes. Looks like you might have to. If you take a look at the scan example
you can see how to take a rust closure and pass it to the onig_sys API. If
you get stuck feel free to ask more questions. You're also welcome to open
a pull request with your first cut at the code and we can discuss the best
options.

If you don't feel you want to implement t the extra API stuff that's cool
too, so long as you don't mind waiting a few days for me to have a go at
it.

**Comment by b52** [comment]
No it's fine, I don't mind implementing it. Again, I'll see how far I come and might open a PR intermediately to discuss the options.

**Comment by iwillspeak** [comment]
All done
