### ISSUE TITLE
is_match() and find().is_some() give different results

### ISSUE THREAD

**Issue by msehnout** [rust-onig/rust-onig#34]
When working on Advent of code examples, I came across this issue. `is_match` method gives different results from `find` followed by `is_some` although I think it should return the same. 

For instance:
```rust
extern crate onig;

use onig::Regex;

fn main() {
    let ipv7 = "abba[mnop]qrst";
    let abba = Regex::new(r#"(\w)(?!\1)(\w)\2\1"#).unwrap();
    if abba.find(ipv7).is_some() {
        println!("Found pattern");
    } else {
        println!("Pattern not found");
    }
    if abba.is_match(ipv7) {
        println!("Found pattern");
    } else {
        println!("Pattern not found");
    }

}
```
Gives this output:
```bash
$ cargo run
Found pattern
Pattern not found
```

Is this a bug or am I using it wrong?

**Comment by iwillspeak** [comment]
Hi, and thanks for choosing `onig`. I'm enjoying Advent of Code too.

`find` searches for the pattern within the string and returns information about where it found it. `is_match` On the other hand checks if the _whole_ string matches the pattern. So yes, they do different things.

Hope this helps. Let me know if you needs more clarification. 

I've just had a look at [the docs](https://docs.rs/onig/1.1.0/onig/struct.Regex.html#method.is_match) and I can see how it could be confusing.  I'll update it to be a bit clearer about `id_match`'s behaviour.

**Comment by iwillspeak** [comment]
Hopefully the [`Regex::is_match`](https://docs.rs/onig/1.2.0/onig/struct.Regex.html#method.is_match) and [`Rege::find`](https://docs.rs/onig/1.2.0/onig/struct.Regex.html#method.find) documentation is a bit clearer now.

I've also added a larger section which discusses the difference between the [match and search APIs](https://docs.rs/onig/1.2.0/onig/index.html#match-vs-search)

**Comment by msehnout** [comment]
Thanks, now it's clear :-)
