### ISSUE TITLE
Build breaks on Windows with nightly rustc

### ISSUE THREAD

**Issue by Ruin0x11** [rust-onig/rust-onig#40]
Trying to build `rust-onig` on Windows with the nightly toolchain gives this for me:

```
error: failed to run custom build command for `onig_sys v63.0.2`
process didn't exit successfully: `c:\Users\Prin\build\oxidoc\target\debug\build
\onig_sys-165165d91a6214d3\build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Build error:
STDERR:
Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1065: invalid option '-'
Stop.

STDOUT:
C:\Users\Prin\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-63.0.2\on
iguruma>cd src

C:\Users\Prin\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-63.0.2\on
iguruma\src>copy config.h.win64 config.h
        1 file(s) copied.

C:\Users\Prin\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-63.0.2\on
iguruma\src>nmake -f Makefile.windows
', C:\Users\Prin\.cargo\registry\src\github.com-1ecc6299db9ec823\onig_sys-63.0.2
\build.rs:57
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

After looking around, I noticed the issue might have to do with the `MAKEFLAGS` environment variable. I made sure to unset it before running `cargo build` but the error still happens. However, running an `env | grep MAKE` just before the build command, it shows that `MAKEFLAGS` is set to this:

```
MAKEFLAGS=--jobserver-fds=__rust_jobserver_semaphore_2345838727 --jobserver-auth
=__rust_jobserver_semaphore_2345838727
```

These are messing up the `nmake` command. Unsetting them just before the `nmake` command in `make_win64.bat` lets the build run normally. Apparently [this commit](https://github.com/alexcrichton/cargo/commit/cbf25a9b0ae5ac6f5b6da96e645b7fa6a75dc245) added some arguments to `MAKEFLAGS` that confuse `nmake`.

```
> cl
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

> rustc --version
rustc 1.19.0-nightly (fe7227f6c 2017-06-16)
```

**Comment by iwillspeak** [comment]
Oh dear. I guess the solution to this is to remove `MFLAGS` and `MAKEFLAGS` from the environment in the build script as Rust does for tests. Do you want to open a pull request for this, or are you happy to wait until I have time to tackle it?

**Comment by iwillspeak** [comment]
I've kicked off [a new build](https://ci.appveyor.com/project/iwillspeak/rust-onig/build/1.0.120) as a record of how Appveyor builds this.
