### ISSUE TITLE
Failed on Linux Mint 18

### ISSUE THREAD

**Issue by codeyash** [rust-onig/rust-onig#43]
git clone repo
    cargo build

  Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling libc v0.2.26
   Compiling bitflags v0.7.0
   Compiling lazy_static v0.2.8
   Compiling gcc v0.3.51
   Compiling pkg-config v0.3.9
   Compiling cmake v0.1.24
   Compiling onig_sys v64.0.0 (file:///home/yash/Projects/Fresh/gui/research-sources/rust-onig/onig_sys)
error: failed to run custom build command for `onig_sys v64.0.0 (file:///home/yash/Projects/Fresh/gui/research-sources/rust-onig/onig_sys)`
process didn't exit successfully: `/home/yash/Projects/Fresh/gui/research-sources/rust-onig/target/debug/build/onig_sys-7db7e7810c98c6f1/build-script-build` (exit code: 101)
--- stdout
running: "cmake" "/home/yash/Projects/Fresh/gui/research-sources/rust-onig/onig_sys/oniguruma" "-DBUILD_SHARED_LIBS=OFF" "-DCMAKE_INSTALL_PREFIX=/home/yash/Projects/Fresh/gui/research-sources/rust-onig/target/debug/build/onig_sys-4629b99d11a8ec71/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_BUILD_TYPE=Debug"

--- stderr
CMake Error: The source directory "/home/yash/Projects/Fresh/gui/research-sources/rust-onig/onig_sys/oniguruma" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
thread 'main' panicked at '
command did not execute successfully, got: exit code: 1

build script failed, must exit now', /home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.24/src/lib.rs:593
note: Run with `RUST_BACKTRACE=1` for a backtrace.

**Comment by iwillspeak** [comment]
This looks like the oniguruma submodule isn't checked out. I can get the same error on a clean checkout.

Try running `git submodule init --update` and then re-building.
