### ISSUE TITLE
Failed in another project

### ISSUE THREAD

**Issue by codeyash** [rust-onig/rust-onig#44]
/home/yash/.cargo/registry/src/github.com-1ecc6299db9ec823/onig_sys-64.0.0/oniguruma/src/regint.h:667:9: error: unknown type name ‘intptr_t’
typedef intptr_t OnigStackIndex;

https://github.com/trishume/syntect/issues/89

I'm not sure if it's rust-onig issue or syntect but since it's clearly failing on onig I included a report here. For details please click on above link.

**Comment by iwillspeak** [comment]
This _is_ an onig issue. I'm looking into it as #42. Thanks for the report though!

What OS and rust versions are you using?
