### ISSUE TITLE
Replace with captured groups?

### ISSUE THREAD

**Issue by DoumanAsh** [rust-onig/rust-onig#59]
I'm not sure if it good idea, but I noticed that there is lack of replacing with capturing groups.
I.e.

```rust
let re = Regex::new("(.*)\s+(.*)").unwrap();
let result = re.replace_all("first second", "$2 $1");
```

Result will be just "$2 $1".

I tried to look into inguruma itself but I didn't find replacement functionality there so I guess rust-onig implements it on its own?
If so then I would just like to highlight that this feature may be useful, but if it is not worth it to implement, then the request can be closed :)

**Comment by iwillspeak** [comment]
You are right, `onig` implements replacement. The second argument to the `replace` family of fuctions is a `Replacer`. This can either be a literal string, a callback which takes the capture group and returns a astring, or some custom instance of your own type.

If you want to use the captures in the replacement the quickest way would probably be to format the captures yourself:

```rust
let result = re.replace_all("first second", |caps: &Captures| {
    format("{} {}", caps.at(1).unwrap(), caps.at(2).unwrap())
});
```

Check out [the docs](https://docs.rs/onig/2.0.1/onig/struct.Regex.html#method.replace) for more information.

**Comment by DoumanAsh** [comment]
But `onig` doesn't support `$1` and etc when providing only replacement string, right?

**Comment by iwillspeak** [comment]
No. The replacements that `onig` supports out of the box are:

 * Literal strings, with no support for capture group references
 * Callbacks to produce a replacement from the captured content

You could add support for dollar-string syntax quite easily though:

```rust
use onig::{Regex, Replacer, Captures};
use std::borrow::Cow;

/// A string, with `$1` refering to the first capture group.
struct Dollarified<'a>(&'a str);

impl <'a> Replacer for Dollarified<'a> {
    fn reg_replace(&mut self, caps: &Captures) -> Cow<str> {
        let mut replacement = self.0.to_owned();
        for i in 1..caps.len() {
            replacement = replacement.replace(
                &format!("${}", i),
                caps.at(i).unwrap());
        }
        replacement.into()
    }
}

fn main() {
    let re = Regex::new(r"(\w+) (\w+)").unwrap();
    let hay = "hello world";
    println!("{} -> {}", &hay, re.replace(hay, Dollarified("$2 $1")));
}
```

I can't vouch for the efficiency of the above code. If you know the format of the replacement then using a closure instead is going to be quicker.

**Comment by DoumanAsh** [comment]
Ok, I see.
Then I suppose user should go with callback to handle it.
Thanks.

**Comment by iwillspeak** [comment]
I've added [an example](https://github.com/rust-onig/rust-onig/blob/c73def103941ffbaa2f765de53d299b1701fb8f4/examples/dollar.rs) which shows a better implementation of dollar replacement strings. It is probably something we _should_ support in this crate. More work is needed though to decide on the exact replacement syntax (do we support named captures, what does an invalid number expand to and so on).

Thanks for the question though!
