### ISSUE TITLE
Make Static Linking the default for _all_ Platforms

### ISSUE THREAD

**Issue by iwillspeak** [rust-onig/rust-onig#65]
Following on from #38, #63 and the [discussion around the removal of feature-flag linking](https://github.com/rust-onig/rust-onig/commit/679348dc2a1966e0d748378a8ef365e2597e538a#commitcomment-25581511).

At the moment the default link type is static for MUSL and MSVC, and dynamic for all other platforms. There is an argument that dynamic linking goes against the default expectations of Rustaceans, with crates normally being statically linked into the final binary. The counter argument is that we should try to link to libraries in the way that most fits in with the target platform's social mores.

So, the question is "should static linking be the default?"

For those in favour of changing static linking to be the default for _all_ platforms, not just MUSL and MSVC react with 👍 . For those in favour of dynamic linking react with 👎  .

**Comment by retep998** [comment]
My opinion is if the crate has to build the library itself from source, then it should definitely be statically linked. If the system only has it as dynamic or static but not both, then just link the form that is available. If the system has the library in both dynamic and static forms, then I'm not sure which to prefer.

**Comment by trishume** [comment]
I agree with @retep998 that the best option would be to look at what's available and decide from there. In the ambiguous case mentioned of both static and dynamic being available from the system, I think static is a good default because Rust crates generally use static linking and it seems the least surprising for people who might try to distribute a binary they build on their system.

**Comment by est31** [comment]
I think this is the best outcome. For the non-distro use case, static linking is the best. Distributions however can easily set environment variables to enable dynamic linking, this is easier than doing this through a cargo feature (that would have to be passed through the entire dependency foodchain).
