### ISSUE TITLE
Expose all Oniguruma API Functions in `onig_sys`

### ISSUE THREAD

**Issue by iwillspeak** [rust-onig/rust-onig#7]
- [x] Add extern declarations for all Oniguruma functions to the `onig_sys` crate.
- [x] Add documentation comments for all exported functions in the crate.
- [x] Add structure definitions for all remaining C structures
- [x] Add constant declarations for all C constants.
- [x] Add extern declaration for undocumented functions. #8

**Comment by iwillspeak** [comment]
As of 464dbd4 all of the Oniguruma functions from the API reference are declared in the `onig_sys` crate. I think we can move towards making this crate stable now. Unless there's anything else you think needs doing in `onig_sys` @defuz I suggest we bump the version of that crate all the way to *1.0*.

**Comment by defuz** [comment]
@iwillspeak I want to change the definition of types like `OnigRegex` from `c_void` to real struct definition in the near future. It is necessary to implement some things in `onig` crate. I think it should to be done **before** 1.0.

**Comment by defuz** [comment]
Another missed feature in `onig_sys` is definition of constants like `OPTION_*`, `OPERATOR_*`, `BEHAVIOR_*`.

Ideally API of `onig_sys` should be fully comply with `oniguruma.h`:

https://github.com/kkos/oniguruma/blob/master/oniguruma.h

**Comment by iwillspeak** [comment]
I've added all of the functions mentioned in #8. I think that all of the required constants are now exported too so I'm closing this issue. Guess we can create a new issue if there still seem to be bits missing.
