### ISSUE TITLE
Upgrade to Latest Release (6.8.0)

### ISSUE THREAD

**Issue by iwillspeak** [rust-onig/rust-onig#75]
This release adds a few new API points we should wrap. 

 * [x] ~~Callback support~~ moved to #81
 * [x] Search with param and match with param

<https://github.com/kkos/oniguruma/releases/tag/v6.8.0>

**Comment by robinst** [comment]
This is also very interesting: https://github.com/kkos/oniguruma/blob/v6.8.1/HISTORY#L21

It turns on the `USE_TRY_IN_MATCH_LIMIT` define (old name was `USE_COMBINATION_EXPLOSION_CHECK`). I discovered that just now as I was looking into adding a feature to rust-onig to enable it.

I have a change locally, and when the limit is reached, it returns `ONIGERR_TRY_IN_MATCH_LIMIT_OVER` (-17). rust-onig currently doesn't handle that in a special way, so it panics with a "Onig: Internal error during regex match".

Do you think we should have a more specific panic message in that case? Even better would be a Result that includes that error, but the current signatures all return `Option`. Even returning `None` might be an option, but it might be misleading as reaching the limit doesn't mean that there's no match.

(CC @trishume and @keith-hall, this is very interesting for syntect to be able to stop in case of exponential backtracking.)

**Comment by iwillspeak** [comment]
Interesting. I'm working on exposing the `MatchParams` at the moment. When done we'd need an extra overload of `search_` and friends. Guess that they could return `Result`. As for the better `panic!` message: definitely. We should be converting the error to a string and including that. I'll create an issue for fixing that.

**Comment by robinst** [comment]
Yes, the new `search_` methods returning `Result` sounds good.

Do you need any help for doing this? I could lend a hand if you want. I guess one of the things would be adding a `set_retry_limit_in_match` method?

**Comment by robinst** [comment]
And raised another PR for adding `match_with_param` and `search_with_param` which return `Result<Option<usize>, Error>`: #80.

**Comment by robinst** [comment]
What's the plan for the callout APIs? Looks like they're experimental for now.

**Comment by iwillspeak** [comment]
Thinking that I'll split support for those off into a separate issue so we can get this PR merged and published.
