### ISSUE TITLE
Create Better Panic Message when Search Fails 

### ISSUE THREAD

**Issue by iwillspeak** [rust-onig/rust-onig#77]
At the moment a generic `"Onig: Internal error during regex match" ` panic message is raised if a match doesn't complete successfully. Update this to convert the error code to a string properly.

This should be a case of updating the following line in `src/lib.rs`:
https://github.com/rust-onig/rust-onig/blob/master/src/lib.rs#L452

The panic message should use `onig_sys::onig_error_code_to_str` with a `null` error info in a similar way to the `Error` struct here:

https://github.com/rust-onig/rust-onig/blob/master/src/lib.rs#L148

**Comment by robinst** [comment]
Working on this.

**Comment by robinst** [comment]
See pull request #78
