### ISSUE TITLE
Should we use the original names for the types?

### ISSUE THREAD

**Issue by defuz** [rust-onig/rust-onig#9]
I'm a little concerned that the names of some struct's in onig_sys do not equal to the original names.

Original names:

- OnigCaseFoldType
- OnigOptionType
- OnigMetaCharTableType
- OnigEncodingType
- OnigSyntaxType

We use:

- OnigCaseFold
- OnigOptions
- OnigMetaCharTable
- OnigEncoding
- OnigSyntax

On the one hand, I do not see much sense to use `Type` word in the names of structures. On the other hand, compliance with the original API may be more important than our sense of beauty and traditions in Rust. @iwillspeak what you think?

**Comment by iwillspeak** [comment]
I agree that the Type suffix is superfluous. I think how we that we should
stick to the original API spec and use the suffix in onig_sys. We can use
whatever names we like in the main onig crate but other people might want
to use onog_sys for direct bindings to oniguruma so we should export that
API as close to the original as Rust allows us to.

**Comment by defuz** [comment]
I renamed all types to the original name.

**Comment by iwillspeak** [comment]
:thumbsup:
