### ISSUE TITLE
test for version is unreliable

### ISSUE THREAD

**Issue by ignatenkobrain** [rust-onig/rust-onig#93]
We are not using bundled version of oniguruma in onig_sys which means that it might be different from what test expects.

```rust
---- utils::tests::utils_get_version_returns_expected_version stdout ----
thread 'utils::tests::utils_get_version_returns_expected_version' panicked at 'assertion failed: `(left == right)`
  left: `"6.8.2"`,
 right: `"6.9.0"`', src/utils.rs:54:9
```

**Comment by iwillspeak** [comment]
Hmm. Does it matter that that test fails? It should only really need to be run if you’re developing a feature for `onig` itself. I have thought about removing that test before. It is useful for proving you’re linked to the version of onigurima you expect though. At least in some cases.
